### ISSUE TITLE
Crashes for apks build with minSdkVersion 24 or greater

### ISSUE THREAD

**Issue by grepx** [TestArmada/flank#165]
Hi,
I'm using the latest release (flank-v2.0.3.jar) and getting the following crash on apks built with minSdkVersion 24 or greater:

```com.linkedin.dex.spec.DexException: Invalid dexMagic:
DexMagic(dex=[100, 101, 120], newline=10, version=[48, 51, 55], zero=0)
DexMagic(dex=[100, 101, 120], newline=10, version=[48, 51, 53], zero=0)
	at com.linkedin.dex.spec.DexMagic.validate(DexMagic.kt:31)
	at com.linkedin.dex.spec.HeaderItem.validate(HeaderItem.kt:62)
	at com.linkedin.dex.spec.DexFile.<init>(DexFile.kt:35)
	at com.linkedin.dex.parser.DexParser$Companion$readDexFiles$1$4.invoke(DexParser.kt:79)
	at com.linkedin.dex.parser.DexParser$Companion$readDexFiles$1$4.invoke(DexParser.kt:23)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:147)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:630)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:660)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:651)
	at com.linkedin.dex.parser.DexParser$Companion.readDexFiles(DexParser.kt:80)
	at com.linkedin.dex.parser.DexParser$Companion.findTestMethods(DexParser.kt:58)
	at com.linkedin.dex.parser.DexParser.findTestMethods(DexParser.kt)
	at com.walmart.otto.Flank.getTestCaseNames(Flank.java:268)
	at com.walmart.otto.Flank.start(Flank.java:71)
	at com.walmart.otto.Flank.main(Flank.java:118)
```

Other than that this is a very useful project and has solved a lot of problems for me so thanks for all your hard work!

**Comment by bootstraponline** [comment]
Issue has been fixed upstream. Flank will upgrade to the fixed version once there's a new release:
https://github.com/linkedin/dex-test-parser/issues/15

**Comment by bootstraponline** [comment]
Flank has been updated.

https://github.com/TestArmada/flank/releases/tag/flank_snapshot

If this still happens on the new release, comment and let me know.
