### ISSUE TITLE
SocketTimeOutException when running flank

### ISSUE THREAD

**Issue by rashiq** [TestArmada/flank#334]
We're sometimes getting a `SocketTimeOutException`. I'm investigating on how to reproduce this.

```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (ftl.cli.firebase.test.android.AndroidRunCommand@c8b96ec): java.net.SocketTimeoutException: Read timed out
	at picocli.CommandLine.execute(CommandLine.java:914)
	at picocli.CommandLine.access$700(CommandLine.java:104)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1083)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1051)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:959)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1242)
	at picocli.CommandLine.run(CommandLine.java:1701)
	at picocli.CommandLine.run(CommandLine.java:1647)
	at ftl.Main$Companion.main(Main.kt:38)
	at ftl.Main.main(Main.kt)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:105)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at ftl.gc.GcToolResults.getResults(GcToolResults.kt:67)
	at ftl.json.SavedMatrix.finished(SavedMatrix.kt:58)
	at ftl.json.SavedMatrix.update(SavedMatrix.kt:42)
	at ftl.run.TestRunner.pollMatrices(TestRunner.kt:199)
	at ftl.run.TestRunner.newRun(TestRunner.kt:286)
	at ftl.run.TestRunner$newRun$1.doResume(TestRunner.kt)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:41)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:140)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:70)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking(Builders.kt:46)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.experimental.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Unknown Source)
	at ftl.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:28)
	at picocli.CommandLine.execute(CommandLine.java:906)
	... 9 more
```

**Comment by bootstraponline** [comment]
@rashiq what is the output of `flank --version`?

**Comment by rashiq** [comment]
it's the latest snapshot

**Comment by bootstraponline** [comment]
The Google client `execute()` calls should use a custom execute that retries by default.

```kotlin
fun <T> AbstractGoogleJsonClientRequest<T>.executeWithRetry(): T {
    var lastErr: IOException? = null

    for (i in 1..10) {
        try {
            return this.execute()
        } catch (err: IOException) {
            lastErr = err
            System.err.println("Request failed, retrying ${i}x $err")
        }
    }

    throw IOException("Request failed", lastErr)
}```

**Comment by rpappalax** [comment]
i'm seeing same issue intermittent right after I set testShards: -1, though don't know if related

**Comment by bootstraponline** [comment]
`testShards: -1` creates the most amount of shards. If the FTL API flakes out then it's more likely to trigger the exception.

I've implemented the following fixes:

- A TimeoutHttpRequestInitializer now sets the connect and read to 60 seconds. This is an increase over the 20 second default.
- executeWithRetry is used to retry IOException up to 10x

https://github.com/TestArmada/flank/pull/337

This will be available in the next release of Flank (and immediately in the snapshot release once the PR is merged).
