### ISSUE TITLE
physical devices alway throw "400 Bad Request" error

### ISSUE THREAD

**Issue by rpappalax** [TestArmada/flank#353]
I've tried executing tests on a number of virtual devices (specified in flank.yml) and they all seem to work.  By contrast all of the physical devices I've tried have thrown this error.

```
      device:
        - model: potter
          version: 24
          locale: en
          orientation: portrait
        - model: cheryl
          version: 25
          locale: en
          orientation: portrait

    flank:
      testShards: -1
      repeatTests: 1
      test-targets-always-run:

RunTests
  31 tests / 31 shards = 1 test per shard

Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (ftl.cli.firebase.test.android.AndroidRunCommand@7807ac2c): com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Given test timeout of 60 min exceeds limit of 30 min.",
    "reason" : "badRequest"
  } ],
  "message" : "Given test timeout of 60 min exceeds limit of 30 min.",
  "status" : "INVALID_ARGUMENT"
}
	at picocli.CommandLine.execute(CommandLine.java:914)
	at picocli.CommandLine.access$700(CommandLine.java:104)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1083)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1051)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:959)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1242)
	at picocli.CommandLine.run(CommandLine.java:1701)
	at picocli.CommandLine.run(CommandLine.java:1647)
	at ftl.Main$Companion.main(Main.kt:38)
	at ftl.Main.main(Main.kt)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Given test timeout of 60 min exceeds limit of 30 min.",
    "reason" : "badRequest"
  } ],
  "message" : "Given test timeout of 60 min exceeds limit of 30 min.",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1067)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at ftl.run.AndroidTestRunner$runTests$$inlined$repeat$lambda$1.doResume(AndroidTestRunner.kt:41)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)```

**Comment by bootstraponline** [comment]
`timeout: 30m` will fix

**Comment by rpappalax** [comment]
> `timeout: 30m` will fix

indeed it did.  thank you!
