### ISSUE TITLE
Flank-1.3.0 Crashes - Can't run program gcloud

### ISSUE THREAD

**Issue by JaySoyer** [TestArmada/flank#45]
Was trying to test Flank but can't get it to execute correctly.  

- Using Powershell though also tried Google Cloud SDK Shell
- Windows 10 Version 1703 Build 15063.413
- Google Cloud SDK 159.0
- Have gcloud beta 2017.03.24 installed as well
- Using Flank-1.3.0
- java version 1.8.0_131

Running command as follows:
`java -jar Flank-1.3.0.jar app\build\outputs\apk\app-debug.apk app\build\outputs\apk\app-debug-androidTest.apk com.amazonaws.devicefarm.android.referenceapp`

Am greeted with this error message.  Note gcloud command is working fine for me when used outside of Flank.
> java.io.IOException: Cannot run program "gcloud": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at com.walmart.otto.tools.ProcessBuilder.start(ProcessBuilder.java:24)
        at com.walmart.otto.tools.ProcessExecutor.executeCommand(ProcessExecutor.java:31)
        at com.walmart.otto.tools.Tool.executeCommand(Tool.java:69)
        at com.walmart.otto.tools.GcloudTool.getProjectName(GcloudTool.java:118)
        at com.walmart.otto.Flank.getProjectName(Flank.java:153)
        at com.walmart.otto.Flank.start(Flank.java:40)
        at com.walmart.otto.Flank.main(Flank.java:73)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 8 more

**Comment by renas** [comment]
The problem is that the gcloud binary can't be found. To resolve it create a config.properties where you set the paths to the binaries by:

gcloud-path:/path/to/gcloud
gsutil-path:/path/to/gsutil

Please see the README for more information.

**Comment by JaySoyer** [comment]
Still not working:
gcloud-path="C:\\\Users\\\Jay\\\AppData\\\Local\\\Google\\\Cloud SDK\\\google-cloud-sdk\\\bin"
gsutil-path="C:\\\Users\\\Jay\\\AppData\\\Local\\\Google\\\Cloud SDK\\\google-cloud-sdk\\\bin"

Right now it's failing on finding gsutil.  I've tried the following variations with no success:
C:\\\Users\\\Jay\\\AppData\\\Local\\\Google\\\Cloud SDK\\\google-cloud-sdk\\\bin
"C:\\\Users\\\Jay\\\AppData\\\Local\\\Google\\\Cloud SDK\\\google-cloud-sdk\\\bin"
"C:\\\Users\\\Jay\\\AppData\\\Local\\\Google\\\Cloud SDK\\\google-cloud-sdk\\\bin\\\gsutil.cmd"
C:\\\Users\\\Jay\\\AppData\\\Local\\\Google\\\Cloud SDK\\\google-cloud-sdk\\\bin\\\gsutil.cmd
"/Users/Jay/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin"
/Users/Jay/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin
"/Users/Jay/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gsutil.cmd"
/Users/Jay/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gsutil.cmd

That location was determined via using `where.exe gsutil` and verified that the *.cmd file is there.

> java.lang.IllegalArgumentException: Gsutil binary not found at provided path: C:/Users/Jay/AppData/Local/Google/CloudSDK/google-cloud-sdk/bin"
        at com.walmart.otto.configurator.Configurator.setGsutil(Configurator.java:97)
        at com.walmart.otto.configurator.ConfigReader.setProperty(ConfigReader.java:83)
        at com.walmart.otto.configurator.ConfigReader.setProperties(ConfigReader.java:23)
        at com.walmart.otto.configurator.ConfigReader.<init>(ConfigReader.java:14)
        at com.walmart.otto.Flank.start(Flank.java:36)
        at com.walmart.otto.Flank.main(Flank.java:73)

**Comment by bootstraponline** [comment]
Hi, thanks for opening an issue on the Flank repo. The Kotlin rewrite is now available for testing and feedback. This replaces the Java version of Flank.

- https://github.com/TestArmada/flank/releases/tag/flank_snapshot

Join us in the`#flank` channel on the Firebase slack to chat. If this is still an issue in the new release, comment and let me know.

-  https://firebase.community/
