### ISSUE TITLE
FetchArtifacts Exception - rewrite user auth flow

### ISSUE THREAD

**Issue by gtroshin** [TestArmada/flank#464]
```
java -jar ./flank.jar -v
v4.2.0
5148c339e697778a3714bfb1aa6d4a9a120c5164
```

There is a failure in the end of test.

```
FetchArtifacts
  Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (ftl.cli.firebase.test.ios.IosRunCommand@767599a7): com.google.cloud.storage.StorageException: java.lang.IllegalStateException: OAuth2Credentials instance does not support refreshing the access token. An instance with a new access token should be used, or a derived type that supports refreshing.
	at picocli.CommandLine.execute(CommandLine.java:1168)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at picocli.CommandLine.run(CommandLine.java:1974)
	at picocli.CommandLine.run(CommandLine.java:1920)
	at ftl.Main$Companion.main(Main.kt:48)
	at ftl.Main.main(Main.kt)
Caused by: com.google.cloud.storage.StorageException: java.lang.IllegalStateException: OAuth2Credentials instance does not support refreshing the access token. An instance with a new access token should be used, or a derived type that supports refreshing.
```

**Comment by bootstraponline** [comment]
Are you using a service account JSON for authorization?

**Comment by bootstraponline** [comment]
This looks like it'll be fun to solve. 😭 

https://github.com/googleapis/oauth2client/issues/391

**Comment by bootstraponline** [comment]
I pushed a hotfix that solves the issue by disabling user auth. Service account auth now won't expire. You can use the snapshot jar which is auto published after every PR.
https://github.com/TestArmada/flank/pull/465

At some point in the future I'll update to the new non-deprecated oauth lib and that will enable supporting user auth in addition to service auth. I'll leave this issue open until then.

**Comment by gtroshin** [comment]
Thanks for the fix! I am testing it now.

**Comment by gtroshin** [comment]
Seems like that issue is gone. Thanks again.

**Comment by bootstraponline** [comment]
Authentication now uses the latest Java lib by Google.
