### ISSUE TITLE
Crash in `SavedMatrix#finished`: IllegalStateException: step.testExecutionStep.testTiming must not be null

### ISSUE THREAD

**Issue by jschear** [TestArmada/flank#498]
We encountered this crash using Flank version v4.2.0, while running 75 shards.

It looks like there's a null check for `step.testExecutionStep`, but in this case `step.testExecutionStep.testTiming` was `null`.

```
10:42:50   4m 48s matrix-285i5yv89ulkl RUNNING
10:43:47   5m 43s matrix-285i5yv89ulkl Non-retryable error occurred during results processing.
10:52:53 Request failed, retrying 1x java.net.SocketTimeoutException: Read timed out
11:02:45   24m 38s matrix-285i5yv89ulkl FINISHED
11:02:45 Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (ftl.cli.firebase.test.android.AndroidRunCommand@6d367020): java.lang.IllegalStateException: step.testExecutionStep.testTiming must not be null
11:02:45     at picocli.CommandLine.execute(CommandLine.java:1168)
11:02:45     at picocli.CommandLine.access$800(CommandLine.java:141)
11:02:45     at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
11:02:45     at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
11:02:45     at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
11:02:45     at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
11:02:45     at picocli.CommandLine.run(CommandLine.java:1974)
11:02:45     at picocli.CommandLine.run(CommandLine.java:1920)
11:02:45     at ftl.Main$Companion.main(Main.kt:48)
11:02:45     at ftl.Main.main(Main.kt)
11:02:45 Caused by: java.lang.IllegalStateException: step.testExecutionStep.testTiming must not be null
11:02:45     at ftl.json.SavedMatrix.finished(SavedMatrix.kt:81)
11:02:45     at ftl.json.SavedMatrix.update(SavedMatrix.kt:57)
11:02:45     at ftl.run.TestRunner.pollMatrices(TestRunner.kt:249)
11:02:45     at ftl.run.TestRunner.newRun(TestRunner.kt:353)
11:02:45     at ftl.run.TestRunner$newRun$1.invokeSuspend(TestRunner.kt)
```

**Comment by bootstraponline** [comment]
Thanks for reporting this bug. I'll push a fix when I'm back next week.

**Comment by bootstraponline** [comment]
One day Google will publish a client library with nullability annotations and we won't have to discover the edge cases by trial and error. 🙂  

I merged the fix to master. The snapshot release will be automatically published in a few minutes.

**Comment by jschear** [comment]
🤞 someday! Thanks for fixing.
