### ISSUE TITLE
Smart Flank XML - Time 0.0

### ISSUE THREAD

**Issue by alistairsykes** [TestArmada/flank#579]
We are getting an exception (shown below) when running flank from CI via bash script.

Version: 6.2.3

After some experimenting it appears to be related to the cached smart xml. Via trial and error, I think it relates to the times being assigned to each testcase. When any of those times have `0.0` against them we get that exception.

My particular situation is that I have some placeholder tests within my code (rightly or wrongly) which effectively just `assertTrue(true)`. So I presume they are running so fast that it's resulting in `0.0` time.

Maybe there should be a minimum time, or perhaps it's a rounding issue. I am not really sure where to look in order to create a pr, so if appropriate could someone point in the right direction.

```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (ftl.cli.firebase.test.android.AndroidRunCommand@669253b7): java.util.NoSuchElementException: List is empty.
	at picocli.CommandLine.execute(CommandLine.java:1168)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at picocli.CommandLine.run(CommandLine.java:1974)
	at picocli.CommandLine.run(CommandLine.java:1920)
	at ftl.Main$Companion.main(Main.kt:41)
	at ftl.Main.main(Main.kt)
Caused by: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:194)
	at ftl.shard.Shard.createShardsByShardCount(Shard.kt:113)
	at ftl.args.ArgsHelper.calculateShards(ArgsHelper.kt:226)
	at ftl.args.AndroidTestShard.getTestShardChunks(AndroidTestShard.kt:26)
	at ftl.run.AndroidTestRunner$runTests$2.invokeSuspend(AndroidTestRunner.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
	at kotlinx.coroutines.internal.ScopeCoroutine.onCompletionInternal$kotlinx_coroutines_core(Scopes.kt:28)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:305)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:230)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:742)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at ftl.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:48)
	at picocli.CommandLine.execute(CommandLine.java:1160)
	... 9 more
```

**Comment by bootstraponline** [comment]
Thank you for reporting this issue. It looks like a bug in Flank. I'll take a look.

**Comment by bootstraponline** [comment]
@alistairsykes are you able to reproduce the problem using Flank snapshot? https://github.com/TestArmada/flank/releases/tag/flank_snapshot

**Comment by bootstraponline** [comment]
I used the [flank sample app](https://github.com/TestArmada/flank/tree/master/test_app) and set the test time to 0 in the smart flank xml.

```yaml
gcloud:
  app: "../test_app/apks/app-debug.apk"
  test: "../test_app/apks/app-debug-androidTest.apk"
flank:
  smart-flank-gcs-path: gs://test-lab-v9cn46bb990nx-kz69ymd4nm9aq/tmp/test_app_android.xml
```

```xml
<testsuites>
<testsuite name="NexusLowRes-28-en-portrait" tests="1" failures="0" errors="0" skipped="0" time="0.694" timestamp="2019-07-25T19:44:15" hostname="localhost">
<testcase name="testPasses" classname="com.example.app.ExampleUiTest" time="0">
<webLink>
https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.bf178d418be9d33e/matrices/4835312659854164907/executions/bs.1e4af1f9b5c9c369
</webLink>
</testcase>
</testsuite>
</testsuites>
```

The sharding worked correctly on Flank snapshot. If you could provide your XML file, that'd be great to help me debug.

**Comment by alistairsykes** [comment]
I still see this issue on snapshot. It runs first time fine, and produces the attached xml. On second run it fails (with a different error on snapshot). I think you guys have done some work on error reporting which is probably why it's a different error.

[snapshot-android.xml.zip](https://github.com/TestArmada/flank/files/3437978/snapshot-android.xml.zip)

```
Invalid shard count. To debug try: flank android run --dump-shards
 args.maxTestShards: -1
 forcedShardCount: 0 
 testCount: 1 
 maxShards: 0 
 shardsCount: 0
Exited with code 3
```

**Comment by alistairsykes** [comment]
I see the same issue on snapshot with a different error message. But I think you guys have done some work on error messages which would explain that. It runs successfully first time and then second time fails with:
```
Invalid shard count. To debug try: flank android run --dump-shards
 args.maxTestShards: -1
 forcedShardCount: 0 
 testCount: 1 
 maxShards: 0 
 shardsCount: 0
Exited with code 3
```

[snapshot-android.xml.zip](https://github.com/TestArmada/flank/files/3437984/snapshot-android.xml.zip)

**Comment by bootstraponline** [comment]
Thanks for the follow up! I'll work on getting the bug resolved next weekend.

**Comment by bootstraponline** [comment]
I added JUnit tests based on the XML you shared.

![image](https://user-images.githubusercontent.com/1173057/62435877-b3c3fd00-b70b-11e9-88b4-ba6c1ab386fd.png)

This uncovered a bug related to very fast tests breaking the smart flank sharding algorithm.

I think I fixed the problem you reported. Please try the new snapshot jar and let me know. I improved the validation logic so we'll get a better error message.

![image](https://user-images.githubusercontent.com/1173057/62435917-dd7d2400-b70b-11e9-9800-c8503483aab9.png)

---

The root problem is the test time from FTL is wrong. 

 The testsuite time is 12 seconds`<testsuite time="12.032"`

`<testcase "0.026" + "0.001" + "0.001" + "0.028"  + "0.001" + "0.027" + "0.025" + "0.026" + "0.025"+ "0.0">`

Adding up every test case time results in `0.16` seconds. I'm hoping FTL resolves the issue of invalid test time data. At least I can fix the crash for now though.

**Comment by alistairsykes** [comment]
I have just tried it on snapshot and yes its not crashing anymore. Thank you very much.
