### ISSUE TITLE
Unable to write coverage report to /sdcard on Firebase Test Lab emulator

### ISSUE THREAD

**Issue by pjakubczyk** [TestArmada/flank#616]
Does anybody else has problem with writing coverage report to `/sdcard` ?
I see such stacktrace
```
1-08 12:50:36.434: E/CoverageListener(7255): Failed to generate Emma/JaCoCo coverage. 
11-08 12:50:36.434: E/CoverageListener(7255): java.lang.reflect.InvocationTargetException
11-08 12:50:36.434: E/CoverageListener(7255): 	at java.lang.reflect.Method.invoke(Native Method)
11-08 12:50:36.434: E/CoverageListener(7255): 	at androidx.test.internal.runner.listener.CoverageListener.generateCoverageReport(CoverageListener.java:101)
11-08 12:50:36.434: E/CoverageListener(7255): 	at androidx.test.internal.runner.listener.CoverageListener.instrumentationRunFinished(CoverageListener.java:70)
11-08 12:50:36.434: E/CoverageListener(7255): 	at androidx.test.internal.runner.TestExecutor.reportRunEnded(TestExecutor.java:92)
11-08 12:50:36.434: E/CoverageListener(7255): 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:65)
11-08 12:50:36.434: E/CoverageListener(7255): 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
11-08 12:50:36.434: E/CoverageListener(7255): 	at {stripped_package_name}.test.MockInstrumentationRunner.onStart(MockInstrumentationRunner.java:98)
11-08 12:50:36.434: E/CoverageListener(7255): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
11-08 12:50:36.434: E/CoverageListener(7255): Caused by: java.io.FileNotFoundException: /sdcard/tempDir/{stripped_test_name}ec (No such file or directory)
11-08 12:50:36.434: E/CoverageListener(7255): 	at java.io.FileOutputStream.open0(Native Method)
11-08 12:50:36.434: E/CoverageListener(7255): 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
11-08 12:50:36.434: E/CoverageListener(7255): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
11-08 12:50:36.434: E/CoverageListener(7255): 	at com.vladium.emma.rt.RT.dumpCoverageData(RT.java:50)
11-08 12:50:36.434: E/CoverageListener(7255): 	... 8 more
```
I've tried both
`coverageFilePath"     : /sdcard/tempDir/`
and
`coverageFilePath"     : /sdcard/`
there is the same Exception thrown.
Since it's a permission denied I tried 
`coverageFilePath: /sdcard/Android/data/{packageName}/`
And the report was written for only last test. Orchestrator cleans up this directory before each test.

both app and test app apk have
```
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

**Comment by bootstraponline** [comment]
Are you using grant permission rule?

**Comment by bootstraponline** [comment]
Also see "Android code coverage" in the Flank readme.

Try gcloud CLI to see if that has the same problem. I don't think this issue is a Flank bug. Configuring your app to generate coverage with orchestrator is a bit complex.R

If gcloud CLI has the same issue, feel free to ask in the #test-lab channel on Slack.

**Comment by pjakubczyk** [comment]
It turned to be problem with Runtime Permissions.
I made update to documentation https://github.com/TestArmada/flank/pull/617
