### ISSUE TITLE
Invalid configuration does not halt run

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#8]
I'd expect the test run to stop on an exception, not proceed with an invalid configuration.

```
$ java -jar flank.jar app.apk test.apk com.instructure.teacher.ui.DeviceTest
java.lang.NumberFormatException: For input string: "25m"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.walmart.otto.configurator.ConfigReader.setProperty(ConfigReader.java:64)
	at com.walmart.otto.configurator.ConfigReader.setProperties(ConfigReader.java:23)
	at com.walmart.otto.configurator.ConfigReader.<init>(ConfigReader.java:14)
	at com.walmart.otto.Flank.main(Flank.java:26)

Local 'flank.tests' found. It contains test execution times used to create shards with configurable durations. Default shard duration is 120 seconds.

Creating bucket: gs://apk-bucket-2017-05-26-11-34

Creating gs://apk-bucket-2017-05-26-11-34/...
Uploading: app.apk to bucket: gs://apk-bucket-2017-05-26-11-34
```

```
$ cat config.properties
debug-prints:true
deviceIds: NexusLowRes
os-version-ids: 25
orientations: portrait
locales: en
shard-timeout: 25m
numShards: -1
```

**Comment by renas** [comment]
Thanks for reporting this.

**Comment by renas** [comment]
Invalid configurations halt run now.
